-- Eliminar plantillas de reglas antiguas en inglés
DELETE FROM rule_templates 
WHERE key IN (
  'APPOINTMENT_ADVANCE_BOOKING',
  'APPOINTMENT_MIN_ADVANCE_HOURS',
  'APPOINTMENT_CANCELLATION_HOURS',
  'APPOINTMENT_MAX_PER_DAY',
  'APPOINTMENT_REMINDER_ENABLED',
  'APPOINTMENT_REMINDER_HOURS',
  'APPOINTMENT_ALLOW_OVERLAPPING',
  'APPOINTMENT_BUFFER_MINUTES',
  'INVOICE_AUTO_GENERATION',
  'INVOICE_PAYMENT_TERMS',
  'INVOICE_INCLUDE_TAX',
  'INVOICE_TAX_RATE',
  'INVOICE_LATE_PAYMENT_FEE',
  'INVOICE_SEND_EMAIL',
  'INVOICE_REQUIRE_SIGNATURE',
  'INVOICE_NUMBERING_FORMAT',
  'BUSINESS_OPERATING_HOURS_START',
  'BUSINESS_OPERATING_HOURS_END',
  'PAYMENT_METHODS_CASH',
  'PAYMENT_METHODS_CARD',
  'SPECIALIST_COMMISSION_ENABLED',
  'SPECIALIST_DEFAULT_COMMISSION_RATE',
  'REFUND_POLICY_ENABLED',
  'REFUND_POLICY_DAYS'
);

-- Verificar reglas restantes
SELECT key, description FROM rule_templates ORDER BY key;
